/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.SQLException;
import java.util.Arrays;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author silva
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial_new
     */
    public TelaInicial() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jLabel1.setText("Usuário:");

        jLabel2.setText("Senha:");

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/InterrogativeIcon.jpg"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel10.setText("JOVEM AMBIENTALISTA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnLogin)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtPassword))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel10)
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel10)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        try {
                    String user = txtUser.getText();
                    
                    if (!user.isEmpty()) {
                        String senha = txtPassword.getText();
                        System.out.println(senha);
                        boolean authorize = verificaSenha(user, senha);
                        System.out.println(authorize);
                        String nivel = verificaNivelAcesso(user);
                        System.out.println(authorize);
                        setVisible(false);
                        if (authorize) {                                                       
                            switch (nivel) {
                            case "Administrador_Sistema":
                                escolhaTela(1, user);
                                System.out.println("Nivel 1");
                                break;
                            case "Controle_Financeiro":
                                escolhaTela(2, user);
                                System.out.println("Nivel 2");
                                break;
                            case "Controle_Operacional":
                                escolhaTela(3, user);
                                System.out.println("Nivel 3");
                                break;
                            default:
                                break;
                            }
                        }
                        else    JOptionPane.showMessageDialog(null, "Acesso negado. Impressao digital nao reconhecida!");
                    } else
                            JOptionPane.showMessageDialog(null, "O usuario nao existe. Clique no botao Sign Up para cadastrar um novo usuario.");
                } catch (SQLException e1) {
                        e1.printStackTrace();
                }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JOptionPane.showMessageDialog(null, "* Os campos usuario e senha são obrigatorios.\n"
                                + "* Se o usuario nao estiver cadastrado, solicite acesso ao administrador. \n"
                                + "* Se o usuario ja existe no sistema, preencha os campos de usuario e senha, e clique no botao Login. "
                                + "Em seguida, selecione a tela que deseja acessar.");
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }
    
    private String verificaNivelAcesso(String user){
        switch (user){
            case "Admin":
                return "Administrador_Sistema";
            case "Financeiro":
                    return "Controle_Financeiro";
            case "Operacional":
                return "Controle_Operacional";
            default:
                return "None";
        }
    }
    
    private boolean verificaSenha(String user, String senha){
        switch (user){
            case "Admin":
                if("Admin".equals(senha)){
                    System.out.println("Retorna true");
                    return true;
                }
                break;
            case "Financeiro":
                if("Financeiro".equals(senha)){
                    return true;
                }
                break;
            case "Operacional":
                if("Operacional".equals(senha)){
                    return true;
                }
                break;
            default:
                return false;
        }
        return false;
    }
    private void escolhaTela(int x, String user) throws SQLException {
        JList<String> list = new JList<>();
        switch(x){
            case 1:
                list = new JList<>(new String[] {"Usuários", "Serviços", "Produtos", "Estoque", "Financeiro"});
                break;
            case 2:
                list = new JList<>(new String[] {"Financeiro"});                
                break;
            case 3:
                list = new JList<>(new String[] {"Serviços", "Produtos", "Estoque"});
                break;
        }
        JOptionPane.showMessageDialog(
        null, list, "Telas Disponiveis: ", JOptionPane.PLAIN_MESSAGE);
        System.out.println(Arrays.toString(list.getSelectedIndices()));
        String telaEscolhida = list.getSelectedValue();
        switch (telaEscolhida){
            case "Estoque":
            	TelaEstoque telaEst = new TelaEstoque();
                telaEst.setVisible(true);
                this.setVisible(false);
                break;
            case "Usuários":
            	TelaUsuario telaUsu = new TelaUsuario();
                telaUsu.setVisible(true);
                this.setVisible(false);
                break;
            case "Serviços":
            	TelaServicos telaServ = new TelaServicos();
                telaServ.setVisible(true);
                this.setVisible(false);
                break;
            case "Produtos":
                TelaProdutos telaProd = new TelaProdutos();
                telaProd.setVisible(true);
                this.setVisible(false);
                break;
            case "Financeiro":
                TelaFinanceiro telaFin = new TelaFinanceiro();
                telaFin.setVisible(true);
                break;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
